SuperheroesWebApp/Models/ErrorViewModel.cs
using System;

namespace SuperheroesWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperheroesWebApp/Models/Superhero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperheroesWebApp.Models
{
    public class Superhero
    {
        [Key]
        public int SuperheroId { get; set; }
        public string Name { get; set; }
        public string AlterEgo { get; set; }
        public string PrimaryAbility { get; set; }
        public string SecondaryAbility { get; set; }
        public string Catchphrase { get; set; }
        public string RefPicture { get; set; }
        public Superhero()
        {

        }
    }
}

SuperheroesWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperheroesWebApp.Models;

namespace SuperheroesWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperheroesWebApp/Controllers/SuperheroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SuperheroesWebApp.Data;
using SuperheroesWebApp.Models;

namespace SuperheroesWebApp.Controllers
{
    public class SuperheroesController : Controller
    {
        private ApplicationDbContext _context { get; }
        public SuperheroesController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Superheroes
        public ActionResult Index()
        {
            var superheroes = _context.Superhero.Select(a => a);
            return View(superheroes);
        }

        // GET: Superheroes/Details/5
        public ActionResult Details(int id)
        {
            Superhero superhero = _context.Superhero.First(a => a.SuperheroId == id);
            return View(superhero);
        }

        // GET: Superheroes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Superheroes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Superhero superhero)
        {
            try
            {
                // TODO: Add insert logic here
                _context.Superhero.Add(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Superheroes/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var superhero = _context.Superhero.First(a => a.SuperheroId == id);
                return View(superhero);
            }
            catch
            {
                return View();
            }
        }

        // POST: Superheroes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Superhero superhero)
        {
            try
            {
                // TODO: Add update logic here
                Superhero foundSuperhero = _context.Superhero.First(a => a.SuperheroId == id);
                foundSuperhero.Name = superhero.Name;
                foundSuperhero.PrimaryAbility = superhero.PrimaryAbility;
                foundSuperhero.SecondaryAbility = superhero.SecondaryAbility;
                foundSuperhero.AlterEgo = superhero.AlterEgo;
                foundSuperhero.Catchphrase = superhero.Catchphrase;
                foundSuperhero.RefPicture = superhero.RefPicture;
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Superheroes/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Superhero superhero = _context.Superhero.First(a => a.SuperheroId == id);
                return View(superhero);
            }
            catch
            {
                return View();
            }
        }

        // POST: Superheroes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Superhero superhero)
        {
            try
            {
                // TODO: Add delete logic here
                Superhero foundSuperhero = _context.Superhero.First(a => a.SuperheroId == id);
                _context.Remove(foundSuperhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperheroesWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <img class="responsive-pic" src="~/images/deadpool.jpg" alt="Picture" width="500"/>
</div>

SuperheroesWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperheroesWebApp</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperheroesWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link navbar-a" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link navbar-a" asp-area="" asp-controller="Superheroes" asp-action="Index">Superheroes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link navbar-a" asp-area="" asp-controller="Superheroes" asp-action="Create">Create a Superhero</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SuperheroesWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SuperheroesWebApp/Views/Superheroes/Create.cshtml
@model SuperheroesWebApp.Models.Superhero

@{
    ViewData["Title"] = "Create a Superhero";
}

<h1>Create</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catchphrase" class="control-label"></label>
                <input asp-for="Catchphrase" class="form-control" />
                <span asp-validation-for="Catchphrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperheroesWebApp/Views/Superheroes/Delete.cshtml
@model SuperheroesWebApp.Models.Superhero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Catchphrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Catchphrase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RefPicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RefPicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperheroesWebApp/Views/Superheroes/Details.cshtml
@model SuperheroesWebApp.Models.Superhero

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class ="col-sm-2">
            @Html.DisplayNameFor(model => model.RefPicture)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.RefPicture)" alt="Picture of Superhero" height="50"/>            
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Catchphrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Catchphrase)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SuperheroId}) |
    <a asp-action="Index">Back to List</a>
</div>

SuperheroesWebApp/Views/Superheroes/Edit.cshtml
@model SuperheroesWebApp.Models.Superhero

@{
    ViewData["Title"] = "Edit a Superhero";
}

<h1>Edit</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catchphrase" class="control-label"></label>
                <input asp-for="Catchphrase" class="form-control" />
                <span asp-validation-for="Catchphrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RefPicture" class="control-label"></label>
                <input asp-for="RefPicture" class="form-control" />
                <span asp-validation-for="RefPicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
 </div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperheroesWebApp/Views/Superheroes/Index.cshtml
@model IEnumerable<SuperheroesWebApp.Models.Superhero>

@{
    ViewData["Title"] = "List of Superheroes";
}

<h1>Index</h1>

<p>Here are a list of Superheroes</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlterEgo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrimaryAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondaryAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Catchphrase)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlterEgo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrimaryAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecondaryAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Catchphrase)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.SuperheroId }) |
                @Html.ActionLink("Details", "Details", new { id=item.SuperheroId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.SuperheroId })
            </td>
        </tr>
}
    </tbody>
</table>